const photo = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const products = [
  {
    id: 1,
    name: "Cloudline Sofa",
    price: 1299,
    category: "Sofas",
    image: photo("photo-1555041469-a586c61ea9bc"),
    description:
      "Soft lines. A little everyday escape. Our compact, deep-seated sofa brings an effortless sense of calm to your living room.",
    materials: "Performance linen blend, solid kiln-dried hardwood frame",
    dimensions: "78” W × 35” D × 31” H",
    width: 78,
    colors: ["Oatmeal", "Sage", "Charcoal"],
    style: "Modern",
    tag: "SMALL-SPACE FAVORITE",
  },
  {
    id: 2,
    name: "Luna Curved Sofa",
    price: 1599,
    category: "Sofas",
    image: photo("photo-1550254478-ead40cc54513"),
    description:
      "A sculptural silhouette with generous curves, created for conversations that linger.",
    materials: "Ivory bouclé, FSC-certified hardwood, high-density foam",
    dimensions: "90” W × 39” D × 30” H",
    width: 90,
    colors: ["Ivory", "Sand"],
    style: "Organic modern",
    tag: "DESIGNER’S PICK",
  },
  {
    id: 3,
    name: "Forma Coffee Table",
    price: 549,
    category: "Decor",
    image: photo("photo-1533090161767-e6ffed986c88"),
    description:
      "Quietly architectural, with natural grain and a warm finish. The perfect anchor for your living space.",
    materials: "Solid white oak, natural matte oil finish",
    dimensions: "42” W × 24” D × 16” H",
    width: 42,
    colors: ["Natural Oak", "Walnut"],
    style: "Minimal",
    tag: "THE PERFECT PAIRING",
  },
  {
    id: 4,
    name: "Arc Dining Table",
    price: 1099,
    category: "Dining",
    image: photo("photo-1617806118233-18e1de247200"),
    description:
      "A gathering place for your favorite people. An elegant dining table with softly rounded edges, seating six.",
    materials: "Solid European oak, water-based finish",
    dimensions: "72” W × 36” D × 30” H",
    width: 72,
    colors: ["Natural Oak", "Smoked Oak"],
    style: "Scandinavian",
    tag: "MADE FOR GATHERING",
  },
  {
    id: 5,
    name: "Haven Modular Sofa",
    price: 1899,
    category: "Sofas",
    image: photo("photo-1550581190-9c1c48d21d6c"),
    description:
      "Room to relax, your way. Reconfigurable modules and feather-soft cushions grow with your home.",
    materials: "Recycled textured weave, hardwood frame",
    dimensions: "110” W × 62” D × 32” H",
    width: 110,
    colors: ["Oatmeal", "Stone", "Charcoal"],
    style: "Modern",
    tag: "ROOM TO UNWIND",
  },
  {
    id: 6,
    name: "Nook Loveseat",
    price: 999,
    category: "Sofas",
    image: photo("photo-1493663284031-b7e3aefcae8e"),
    description:
      "Small footprint, expansive comfort. Thoughtfully proportioned for apartment living.",
    materials: "Performance cotton blend, ash wood legs",
    dimensions: "62” W × 33” D × 30” H",
    width: 62,
    colors: ["Sand", "Sage"],
    style: "Scandinavian",
    tag: "COMPACT COMFORT",
  },
  {
    id: 7,
    name: "Solstice Lounge Chair",
    price: 649,
    category: "Decor",
    image: photo("photo-1567538096630-e0c55bd6374c"),
    description:
      "Your own little corner of calm. A sculpted accent chair for reading, resting, and everything in between.",
    materials: "Woven linen, solid ash frame",
    dimensions: "29” W × 32” D × 33” H",
    width: 29,
    colors: ["Ivory", "Terracotta"],
    style: "Organic modern",
    tag: "A QUIET MOMENT",
  },
  {
    id: 8,
    name: "Aster Dining Chair",
    price: 249,
    category: "Dining",
    image: photo("photo-1598300042247-d088f8ab3a91"),
    description:
      "A beautifully simple seat, thoughtfully shaped for long evenings around the table. Priced individually.",
    materials: "Solid oak, upholstered linen seat",
    dimensions: "20” W × 22” D × 31” H",
    width: 20,
    colors: ["Oak", "Walnut"],
    style: "Scandinavian",
    tag: "EVERYDAY ELEGANCE",
  },
  {
    id: 9,
    name: "Still Upholstered Bed",
    price: 1499,
    category: "Bedroom",
    image: photo("photo-1505693416388-ac5ce068fe85"),
    description:
      "A soft landing at the end of the day. A queen bed with a generously padded headboard. Mattress not included.",
    materials: "Linen blend, solid wood frame, beech slats",
    dimensions: "66” W × 86” D × 44” H",
    width: 66,
    colors: ["Oatmeal", "Stone"],
    style: "Modern",
    tag: "REST, REIMAGINED",
  },
  {
    id: 10,
    name: "Dune Nightstand",
    price: 349,
    category: "Bedroom",
    image: photo("photo-1499933374294-4584851497cc"),
    description:
      "A beautifully balanced bedside companion with a concealed drawer for everyday essentials.",
    materials: "Oak veneer, solid oak legs, soft-close hardware",
    dimensions: "22” W × 18” D × 24” H",
    width: 22,
    colors: ["Natural Oak", "Walnut"],
    style: "Minimal",
    tag: "BEDSIDE BALANCE",
  },
  {
    id: 11,
    name: "Ora Ceramic Vessel",
    price: 89,
    category: "Decor",
    image: photo("photo-1578500494198-246f612d3b3d"),
    description:
      "An organic, tactile accent for a considered shelf or table. Each hand-finished surface is subtly unique.",
    materials: "Hand-glazed stoneware",
    dimensions: "8” W × 8” D × 12” H",
    width: 8,
    colors: ["Chalk", "Clay"],
    style: "Organic modern",
    tag: "THE FINISHING TOUCH",
  },
  {
    id: 12,
    name: "Linea Console",
    price: 799,
    category: "Decor",
    image: photo("photo-1538688423619-a81d3f23454b"),
    description:
      "Clean lines and natural texture create an inviting first impression in hallways and living spaces.",
    materials: "Solid walnut, brass-finish hardware",
    dimensions: "48” W × 15” D × 30” H",
    width: 48,
    colors: ["Walnut", "Natural Oak"],
    style: "Minimal",
    tag: "A WARM WELCOME",
  },
];
export const shipping =
  "Complimentary delivery on orders over $1,000; $79 flat-rate delivery otherwise. Furniture arrives in 2–4 weeks. Returns accepted within 30 days of delivery in original condition; a $79 collection fee applies. Demo policy only — no actual orders are processed.";
export const money = (n) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
